version: '3.4'

services:
  peer1:
    image: node:latest
    build: .
    working_dir: /app
    volumes:
      - "/p2p:/app"
    command: ["npm", "run", "peerWithFile"]
    ports:
      - 8001:8000

  peer2:
    image: node:latest
    build: .
    working_dir: /app
    volumes:
      - "/p2p:/app"
    command: ["npm", "run", "peer"]
    ports:
      - 8002:8000

  peer3:
    image: node:latest
    build: .
    working_dir: /app
    volumes:
      - "/p2p:/app"
    command: ["npm", "run", "peer"]
    ports:
      - 8003:8000

  peer4:
    image: node:latest
    build: .
    working_dir: /app
    volumes:
      - "/p2p:/app"
    command: ["npm", "run", "peer"]
    ports:
      - 8004:8000
