version: '3.4'

services:
  peer1:
    image: node:latest
    build: .
    working_dir: /app
    volumes:
      - "/p2p:/app"
    command: ["npm", "run", "peer"]

  peer2:
    image: node:latest
    build: .
    working_dir: /app
    volumes:
      - "/p2p:/app"
    command: ["npm", "run", "peer"]

  peer3:
    image: node:latest
    build: .
    working_dir: /app
    volumes:
      - "/p2p:/app"
    command: ["npm", "run", "peer"]
