version: '3.4'

services:
  server1:
    image: node:latest
    build: .
    working_dir: /app
    volumes:
      - "/p2p:/app"
    command: ["npm", "run", "peer"]

  p2p:
    image: node:latest
    build: .
    working_dir: /app
    volumes:
      - "/p2p:/app"
    command: ["npm", "run", "peer"]
