version: '3'

services:
  server:
    image: node:latest
    build: .
    ports:
      - "8001:8000"
    working_dir: /app
    volumes:
      - "/p2p:/app"
    command: ["npm", "run", "server"]

  server1:
    image: node:latest
    build: .
    ports:
      - "8002:8000"
    working_dir: /app
    volumes:
      - "/p2p:/app"
    command: ["npm", "run", "server"]

  p2p:
    image: node:latest
    build: .
    working_dir: /app
    volumes:
      - "/p2p:/app"
    command: ["npm", "run", "p2p"]
